resources:
  - k8s-manifests/base/api.yaml
  - k8s-manifests/base/db.yaml
  - k8s-manifests/base/web.yaml
configMapGenerator:
  - name: db-schema
    files:
      - ./db/words.sql
generatorOptions:
  disableNameSuffixHash: true
